Speed up running of cppyy tests
compiler-research/CppInterOp pull request #271
Opened 2024-05-07 11:41 UTC by mcbarton

The running of the cppyy tests currently takes around 30 minutes to run in the CppInterOp ci, but around 10 minutes in the cppyy repo workflow. This PR should address this issue and allow PR workflows to run almost 3 time quicker. It also allows for greater consistency between the repos in what they are running in their respective workflows.

2024-05-09 14:57 UTC, mcbarton commented
@vgvassilev @maximusron can one of you merge this PR please? It provides an almost 3x speed increase in the time it takes Ubuntu jobs to run. It also provides a reliable number for the code coverage. Previously it was turned on for all Ubuntu jobs instead of just one for some reason. I kept it on for the latest llvm.

2024-05-09 15:16 UTC, maximusron commented
I took a quick look, it looks like quite a few things are being reverted(snap installing valgrind, valgrind commands). 

I think your branch head is at an older point. Can you rebase

2024-05-09 15:20 UTC, mcbarton commented
> @mcbarton I took a quick look, it looks like a few things are being reverted(snap installing valgrind, valgrind commands).
> 
> I think your branch head is at an older point. Can you rebase into a single commit?

@maximusron I made this change to the Valgrind to be consistent with what is in cppyy (see here https://github.com/compiler-research/cppyy/blob/3f284954281610c0f02a255729e6bf8daed63f28/.github/workflows/ci.yml#L768C1-L781C1 ) . If you need to me to change the Valgrind back I can, but I feel it needs to be update in cppyy to be consistent between the repos.

2024-05-09 15:28 UTC, maximusron commented
> @maximusron I made this change to the Valgrind, etc to be consistent with what is in the cppyy repo (see here https://github.com/compiler-research/cppyy/blob/3f284954281610c0f02a255729e6bf8daed63f28/.github/workflows/ci.yml#L768C1-L781C1 for the Valgrind in cppyy) . If you need to me to change the Valgrind back I can, but I feel it needs to be update in cppyy to be consistent between the repos. 


No its the other way around. I have been fixing memory issues on the CI on the InterOp repo and will move these things downstream to cppyy once its done. It is a WIP

2024-05-09 15:36 UTC, maximusron requested changes
I think this can be merged after the jobs are clear

2024-05-09 15:39 UTC, maximusron approved these changes
lgtm! I think this can be merged after the jobs are done

2024-05-09 16:49 UTC, vgvassilev commented
Why the code coverage dropped so drastically?

2024-05-09 16:57 UTC, mcbarton commented
> Why the code coverage dropped so drastically?

@vgvassilev Don't really know why. Previously we had coverage turned on for all llvms (don't know why), so maybe to coverage we get is llvm dependent. Its probably something that needs to be investigated.

2024-05-09 18:05 UTC, vgvassilev commented
Hm, strange. We should have it in one place indeed.

2024-05-12 10:23 UTC, mcbarton commented
@vgvassilev @maximusron Is this PR able to be merged?

2024-05-12 13:04 UTC, vgvassilev approved these changes
LGTM!

2024-05-12 13:04 UTC, merged