Update documentation setup configuration
compiler-research/CppInterOp pull request #99
Opened 2023-06-28 18:33 UTC by Krishna-13-cyber

2023-06-28 22:41 UTC, vgvassilev commented
Why do we need llvm 10? CppInterOp will require some work to enable llvm 10 if possible at all.

2023-06-29 09:02 UTC, Krishna-13-cyber commented
> Why do we need llvm 10? CppInterOp will require some work to enable llvm 10 if possible at all.

The readthedocs supports llvm-version only till llvm-10 and also prior cmake versions.So I had to use these versions for readthedocs compatibilty.

2023-06-29 09:05 UTC, vgvassilev commented
Do we really need to build the codebase with llvm-10? I think if we specified the doxygen build flag we should probably ignore the llvm version checks as we could be only building the doxygen config.

2023-06-29 09:11 UTC, davidlange6 commented
Where can we see this llvm-10 support? I don't immediately find it

> On Jun 29, 2023, at 11:02 AM, Krishna Narayanan ***@***.***> wrote:
> 
> 
> Why do we need llvm 10? CppInterOp will require some work to enable llvm 10 if possible at all.
> The readthedocs supports llvm-version only till llvm-10 and also prior cmake versions.So I had to use these versions for readthedocs compatibilty.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-06-29 09:29 UTC, Krishna-13-cyber commented
> Do we really need to build the codebase with llvm-10? I think if we specified the doxygen build flag we should probably ignore the llvm version checks as we could be only building the doxygen config.

We just need llvm to pass the cmake checks, it is nothing to do with docs generation. I will try to get some alter method  for this

2023-06-29 09:34 UTC, Krishna-13-cyber commented
> Where can we see this llvm-10 support? I don't immediately find it

The llvm-10 support was working for clad but I had upgraded it for interop to llvm-14 but it didnt seem to work well.
Yes, I found it too while building the docs in readthedocs build setup, I will just share a screen capture of build failure (llvm version incompatible).[](url)
![build](https://github.com/compiler-research/CppInterOp/assets/84722531/f01ea77c-07e3-47d6-a9b4-e7dbb9c60df9)

2023-06-29 09:35 UTC, davidlange6 commented
whose cmake checks?

2023-06-29 09:35 UTC, davidlange6 commented
ok, I see your graphic now..

2023-06-29 09:40 UTC, davidlange6 commented
did you consider using conda to do the installs instead?

2023-07-02 07:50 UTC, parth-07 commented
@vgvassilev @davidlange6 If I understand correctly, the pull request is not actually building CppInterOp in the readthedocs configuration. `llvm-10` is only required to run CMake on the CppInterOp. CMake will generate documentation targets. These documentation targets are used to generate sphinx and doxygen docs.

> I think if we specified the doxygen build flag we should probably ignore the llvm version checks as we could be only building the doxygen config.

Yes, this can be done. For this, we will have to add an option such as, 
`CPPINTEROP_BUILD_ONLY_DOCS'. This option can modify CMake to explicitly ignore all configurations
related to building the project. But I don't think this option is required for this change, as we can use `llvm-10`
to bypass the CMake checks.

> did you consider using conda to do the installs instead?

CppInterOp is not being built / installed. Only documentation is being built.

2023-07-02 07:53 UTC, parth-07 requested changes

2023-07-02 07:53 UTC, parth-07 commented on CMakeLists.txt
> +  # if (NOT LLVM_FOUND AND DEFINED LLVM_DIR)
I think this change can be reverted now.

2023-07-02 07:53 UTC, parth-07 commented on CMakeLists.txt
> +  # if (NOT Clang_FOUND AND DEFINED Clang_DIR)
This can be reverted as well.

2023-07-02 08:27 UTC, vgvassilev commented
> @vgvassilev @davidlange6 If I understand correctly, the pull request is not actually building CppInterOp in the readthedocs configuration. `llvm-10` is only required to run CMake on the CppInterOp. CMake will generate documentation targets. These documentation targets are used to generate sphinx and doxygen docs.
> 
> > I think if we specified the doxygen build flag we should probably ignore the llvm version checks as we could be only building the doxygen config.
> 
> Yes, this can be done. For this, we will have to add an option such as, `CPPINTEROP_BUILD_ONLY_DOCS`. This option can modify CMake to explicitly ignore all configurations related to building the project. But I don't think this option is required for this change, as we can use `llvm-10` to bypass the CMake checks.
> 
> > did you consider using conda to do the installs instead?
> 
> CppInterOp is not being built / installed. Only documentation is being built.

Yes, but that change would make it look like we support llvm-10 which we do not. So users with llvm-10 might trigger a build which would then fail. That’s what I am trying to avoid here. The best would be to install the right llvm in the container. The second best would be to use a special cmake flag.

2023-07-02 10:35 UTC, parth-07 commented
> Yes, but that change would make it look like we support llvm-10 which we do not.

Oh, yes you are right. 

> The best would be to install the right llvm in the container. The second best would be to use a special cmake flag.

Yes, this seems right. @Krishna-13-cyber can you please add the special CMake flag for this if we cannot install
right llvm versions?

2023-07-02 12:09 UTC, Krishna-13-cyber commented
> Yes, this seems right. @Krishna-13-cyber can you please add the special CMake flag for this if we cannot install right llvm versions?

Yes, I will get it done!

2023-07-03 09:58 UTC, davidlange6 commented
"llvm-10 is only required to run CMake on the CppInterOp." - this doesn't make much sense to me. Whose limitation is this?

2023-07-03 10:09 UTC, davidlange6 commented
ok, I guess this is because build.image is basically obsolete. I'd suggest we follow build.os instead.. 
https://docs.readthedocs.io/en/stable/tutorial/#adding-a-configuration-file

2023-07-06 05:38 UTC, Krishna-13-cyber commented
> ok, I guess this is because build.image is basically obsolete. I'd suggest we follow build.os instead.. https://docs.readthedocs.io/en/stable/tutorial/#adding-a-configuration-file

I have this approach and works perfect. Thanks!

2023-07-06 05:42 UTC, vgvassilev commented
Can you configure your editor to remove trailing white space?

2023-07-06 09:10 UTC, Krishna-13-cyber commented
> Can you configure your editor to remove trailing white space?

Yes, I will do this but I don't see any trailing spaces here in this PR!

2023-07-12 08:33 UTC, vgvassilev commented on docs/conf.py
> +    "github_user": "vgvassilev",
We should probably use compiler-research.

2023-07-12 17:25 UTC, vgvassilev approved these changes
LGTM!

2023-07-12 17:26 UTC, merged